import React from 'react'
import {FcSmartphoneTablet} from 'react-icons/fc'
import {AiOutlineRight} from 'react-icons/ai'
import { useSelector } from 'react-redux'
import { FaShopify } from 'react-icons/fa'
import { GrWorkshop } from 'react-icons/gr'
import { IoIosApps, IoIosCafe, IoIosConstruct, IoMdShirt, IoMdTennisball } from 'react-icons/io'
import { IoCarSport, IoDesktopSharp} from 'react-icons/io5'

export default function Category() {
    const category =[
        {
            nomi:'smartfon',
            icon:<FcSmartphoneTablet/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoDesktopSharp/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<GrWorkshop/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoIosApps/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoIosCafe/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoIosConstruct/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoMdShirt/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoMdTennisball/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<IoCarSport/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
        {
            nomi:'smartfon',
            icon:<FaShopify/>,
            Smarfonlar:{
                telefonlar:['Smartfonlar',
                    'Samsung smartfonlari',
                   ' iphone',
                   ' HONOR smartfonlari',
                    'Xiaomi smartfonlari',
                   ' Vivo smartfonlari',
                  '  OPPO Smartfonlari',
                  '  TECNO Smartfonlari',
                  '  Huawei smartfonlari',
                 '   Realme Smartfonlari',
                  '  Nothing Phone smartfonlari'],
                gadjetlar:['Tugmachali telefonlar',
                 '   Radiotelefonlar',
                    'Smart soatlar',
                    'Smart tarozi',
                   ' Fitnes soati',
                    "Virtual haqiqat ko'zoynaklari",
                    'Radio aloqa'],
                telefonlarAcsesuarlari:['Tashqi batareyalar',
                    'Smartfonlar uchun ushlagichlar',
                    'Quvvatlash qurilmalari',
                    "O'yin aksessuarlari",
                    "USB kabellar",
                    "Xotira kartalari",
                   " Selfi monopodlari",
                   " Quloqchinlar",
                    "G'ilof",
                    "Himoya oynasi",
                    "AUX kabellar"],
                planshetlar:["Samsung Planshetlar",
                    "{Xiaomi Planshetlar}",
                    "Huawei Planshetlar"],
            }
        },
    ]
    const {categoryopen} = useSelector((state) => state.counter)
  return (
    <div className={`${categoryopen?"top-[100%]":'top-[-800px]'} border-yellow shadow-2xl shadow-black  z-50  absolute   min-w-[300px] border rounded-lg  grid grid-cols-1 bg-white `}>
        
        {
            category.map((x,i)=>(
               <div className={`  flex justify-between items-center border-b-2 p-3 hover:bg-grey0`}key={i} >
                  <button className='flex gap-3 items-center text-xl cursor-pointer ' >{x.icon} {x.nomi} </button>
                <AiOutlineRight/>
               </div>
            ))
        }
    </div>
  )
}
